name: Publish Package

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Build and publish to Github Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./packages/material-tailwind-react
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}